#!/usr/bin/env bash

set -e

DIRNAME=$(dirname $0)
TREK_DIR=$(readlink -f "$DIRNAME/../")

source "$TREK_DIR/lib/trek-dsl"

execute() {
    local query="$1"

    if [ -z "$query" ]; then
        query="$(cat)"
    fi

    echo "$query"
}

assert_equals() {
    if [ "$1" = "$2" ]; then
        echo -n "."
        return 0
    else
        echo "FAILURE:" >&2
        echo "@$2" >&2
        echo "-$1" >&2
        echo
        return 1
    fi
}

test_create_table() {
    local sql=$(create_table users \
        column id "integer" auto_increment \
        column username text \
        column password text)

    local ASSERTION="CREATE TABLE users (id INTEGER AUTO_INCREMENT, username TEXT, password TEXT);"
    
    assert_equals "$ASSERTION" "$sql"
}

test_drop() {
    assert_equals "$(drop_table users)" "DROP TABLE users;"
}

test_add_column() {
    assert_equals "$(add_column users password text)" "ALTER TABLE users ADD COLUMN password TEXT;"
}

test_rename_column() {
    assert_equals "$(rename_column users birth birthday)" "ALTER TABLE users CHANGE COLUMN birth birthday;"
}

test_change_column() {
    assert_equals "$(change_column users birthday DATE)" "ALTER TABLE users MODIFY COLUMN birthday DATE;"
}

test_remove_column() {
    assert_equals "$(remove_column users birthday)" "ALTER TABLE users DROP COLUMN birthday;"
}

test_create_table
test_drop
test_add_column
test_rename_column
test_change_column
test_remove_column

echo
echo "All Tests passed"
