#!/bin/bash
#/ Sends queries received via STDIN to the configured Database
#/
#/ Usage: trek query [<query>]
#/
#/ Queries must be ended with a semicolon!
#/

set -e

DIRNAME=$(dirname $0)
LIB_DIR=$(readlink -f "$DIRNAME/../lib")

source "$DBCONFIG"

# Legacy Behavior
if [ -z "$vendor" ]; then
    vendor=mysql
fi

# This file includes the main interface for vendor extensions
source "$LIB_DIR/vendors/stubs.bash"

# Load the vendor specific commands
source "$LIB_DIR/vendors/$vendor.bash"

query="$(cat)"

if [ -z "$query" ]; then
    trek-help "query" >&2
    exit 1
fi

if [ -z "$database" ]; then
    echo "No Database configured. Please set the \"database\" variable in $DBCONFIG" >&2
    exit 1
fi

if [ -n "$TREK_DEBUG" ]; then
    echo "[DEBUG][QUERY] $query" >&2
fi

vendor_execute <<< "$query"
