#!/usr/bin/env bash
#/ Sets up the Database for usage with Trek
#/
#/ Usage: trek init
#/

VENDOR=$(trek-database-vendor)

source "$TREK_LIB_DIR/vendors/stubs.bash"
source "$TREK_LIB_DIR/vendors/$VENDOR.bash"

create_version_table() {
    trek-query <<SQL
CREATE TABLE trek_version (version TEXT);
INSERT INTO trek_version(version) VALUES ('0');
SQL
}

if vendor_table_exists "trek_version"
then
    echo "Already initialized." >&2
    exit 1
fi

create_version_table
echo "Success! You can now use Trek to migrate your Database"
