#!/bin/bash
#/ Displays Help
#/
#/ Usage: trek help [<command>]
#/

file="$1"

if [ -z "$file" ]; then
    file="$TREK_ROOT/bin/trek"
else
    file="$TREK_LIBEXEC_DIR/trek-$1"
fi

grep '^#/' <"$file" | cut -c4- >&2
